version: "2"

services:
  backend:
    build: .
    command: "gunicorn -w 4 -b 0.0.0.0:8040 --name farmsubsidy_gunicorn \
      --log-level info --log-file /var/log/gunicorn.log farmsubsidy_org.wsgi:application"
    volumes:
      - ./logs/:/var/log/
    ports:
      - 127.0.0.1:8040:8040
    links:
      - elasticsearch
    environment:
      FS_ELASTICSEARCH_URI: http://elasticsearch:9200/
    env_file:
      - farmsubsidy.env

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-log:/var/log
    ports:
      - 127.0.0.1:9240:9200

volumes:
  elasticsearch-data: {}
  elasticsearch-log: {}
