services:
  backend:
    build: .
    restart: unless-stopped
    command: "gunicorn -w 4 -b 0.0.0.0:8000 --name farmsubsidy_gunicorn \
      --log-level info --log-file /var/log/gunicorn.log farmsubsidy_org.wsgi:application"
    volumes:
      - ${DATA_ROOT:-.}/logs/gunicorn:/var/log
    ports:
      - 127.0.0.1:8000:8000
    links:
      - clickhouse
      - redis
    environment:
      DATABASE_URI: clickhouse
      LRU_QUERY_CACHE_SIZE: 1024000000
      REDIS_CACHE_URL: redis://redis
      DJANGO_DEBUG: 0
    env_file:
      - farmsubsidy.env

  clickhouse:
    image: clickhouse/clickhouse-server
    restart: unless-stopped
    volumes:
      - ${DATA_ROOT:-.}/clickhouse-data:/var/lib/clickhouse
      - ${DATA_ROOT:-.}/logs/clickhouse:/var/log/clickhouse-server
    ports:
      - 127.0.0.1:19000:9000
      - 127.0.0.1:18123:8123
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"

  redis:
    image: redis:alpine
    restart: unless-stopped
    expose:
      - 6379
